# ПЗ 21.3 Решение комплексных задач по теме "Функциональные ряды"

{{< include commons/choose-variant-kpz.qmd >}}

## I. Ряды Маклорена

Разложение в ряд Маклорена некоторых элементарных функций:
$${{e}^{x}}=1+\frac{x}{1!}+\frac{{{x}^{2}}}{2!}+\frac{{{x}^{3}}}{3!}+\ldots +\frac{{{x}^{n}}}{n!}+\ldots x\in ( -\infty ;+\infty  )$$ 
$$\sin x=x-\frac{{{x}^{3}}}{3!}+\frac{{{x}^{5}}}{5!}-\ldots +\frac{{{( -1 )}^{n-1}}~{{x}^{2n-1}}}{( 2n-1 )!}+\ldots, x\in ( -\infty ;+\infty  )$$ 
$$\cos x=1-\frac{x^2}{2!}+\frac{{x^4}}{4!}-\ldots+\frac{(-1)^n x^{2n}}{(2n)!}+\ldots,~x\in(-\infty;\infty)$$ 
$$\ln(1+x)=x-\frac{x^2}{2}+\frac{x^3}{3}-\ldots+\frac{(-1)^{n-1}x^n}{n}+\ldots,~x\in(-1;1)$$ 
$$(1+x)^\alpha=1+\frac{\alpha }{1!}x+\frac{\alpha(\alpha-1)}{2!}{{x}^{2}}+\ldots$$
$$+\frac{\alpha(\alpha-1)\ldots( \alpha -n+1)}{n!}{{x}^{n}}+\ldots$$

Примеры. Разложить в ряд Маклорена функцию

:::{.panel-tabset}

## $\sin 3x$
**Решение.**
Так как 
$$\sin x=x-\frac{x^3}{3!}+\frac{x^5}{5!}-\ldots$$
при $x\in (-\infty;+\infty )$, то заменяя $x$ на $3x$ получим
$$\sin 3x=3x-\frac{{{( 3x )}^{3}}}{3!}+\frac{{{( 3x )}^{5}}}{5!}-\ldots +\frac{{{( -1 )}^{n-1}}~{{( 3x )}^{2n-1}}}{( 2n-1 )!}+\ldots =$$
$$=3x-\frac{27~{{x}^{3}}}{3!}+\frac{243~{{x}^{5}}}{5!}-\ldots +\frac{{{( -1 )}^{n-1}}\cdot ~{{3}^{2n-1}}\cdot {{x}^{2n-1}}}{( 2n-1 )!}+\ldots$$

Область сходимости $(-\infty;+\infty)$.



## $\frac{1}{1-x^2}$
**Решение.**
Так как 
$$(1+x)^\alpha=1+\frac{\alpha}{1!}x+\frac{\alpha(\alpha-1)}{2!}x^2+\ldots +$$ 
при 
$$
x\in
\begin{cases}
[-1;1],\alpha\ge0\\
(-1;1], -1<\alpha<0\\
(-1;1),\alpha\le-1\\
\end{cases}
$$
то
$f(x)=\frac{1}{1-x^2}=(1-x^2)^{-1}={{(1+(-{{x}^{2}} ) )}^{-1}}$,
где $\alpha =-1$, вместо $x$ в формулу будем подставлять $-{{x}^{2}}$:
$$f(x)=1+\frac{-1}{1!}(-x^2)+\frac{-1(-1-1)}{2!}{{(-{{x}^{2}} )}^{2}}+\ldots +$$  
$$=1+{{x}^{2}}-{{x}^{4}}+{{x}^{6}}-{{x}^{8}}\ldots,$$
 $-1<x<1$  ;  $0\le {{x}^{2}}<1$    ;  $-1<-{{x}^{2}}\le 0.~~$
Область сходимости $(-1;0]$


## $\ln(1+\frac{x}3)$
**Решение.**
Так как 
$$\ln(1+x)=x-\frac{x^2}{2}+\frac{x^3}{3}-\ldots,$$
при $x\in ( -1;1 )$, то вместо $x$ в эту формулу будем подставлять $\frac{x}{3}$:
$$f(x)=\ln(1+\frac{x}{3})=\frac{x}{3}-\frac{{{(\frac{x}{3})}^{2}}}{2}+\frac{{{( \frac{x}{3} )}^{3}}}{3}-\ldots=$$
$$=\frac{x}{3}-\frac{{{x}^{2}}}{18}+\frac{{{x}^{3}}}{81}-\ldots,$$
где  $-1<x\le 1$, то есть $-3<\frac{x}{3}\le 3$. 
Область сходимости $(-3;3)$


## $\displaystyle\frac{1}{(1+x)^2}$
**Решение.**
Так как 
$$(1+x)^\alpha=1+\frac{\alpha}{1!}x+\frac{\alpha(\alpha -1)}{2!}x^2+\ldots,$$
при 
$$x\in\begin{cases}
   [ -1;1],~~\alpha \ge 0  \\
   (-1;1],~-1<\alpha <0  \\
   (-1;1),~~\alpha \le -1  \\
\end{cases},$$
то
$f(x)=\frac{1}{(1+x)^2}=(1+x)^{-2}$ и  $\alpha =-2$:
$$f(x)=1+\frac{\alpha }{1!}x+\frac{\alpha ~( \alpha -1 )}{2!}{{x}^{2}}+\ldots$$
$$=1-2x+3{{x}^{2}}-4{{x}^{3}}+5{{x}^{4}}\ldots$$  
Область сходимости $(-1;1)$.
:::



### Задание 1. Разложить в ряд Маклорена функцию:

::: {.panel-tabset group='variant' .hide-tabs}

## &nbsp;

$\text{Вариант не выбран}\phantom{\displaystyle\underset{n=1}{\overset{\infty }{\mathop \sum }}\,\frac{( 8n-1 )( 2n+3 )}{( 4n-6 )}}$

$\phantom{\displaystyle\underset{n=1}{\overset{\infty }{\mathop \sum }}\,\frac{\mathrm{arctg}~n}{1+{{n}^{2}}}}$

$\phantom{\displaystyle\underset{n=1}{\overset{\infty }{\mathop \sum }}\,{{( \frac{3{{n}^{2}}+1}{2{{n}^{2}}+1} )}^{n}}}$

$\phantom{\displaystyle\underset{n=1}{\overset{\infty }{\mathop \sum }}\,\frac{3n-2}{{{6}^{n}}}}$


## 1
$$e^{-2x}$$

## 2
$$\cos 8x$$

## 3
$$\ln(3-5x)$$

## 4
$$\sqrt[3]{1+x}$$

## 5
$$\mathrm{arctg}(-\frac{5x}{7})$$

## 6
$$\frac{1}{1+x^4}$$

## 7
$$\sin\left(-\frac{x}{2}\right)$$

## 8
$$e^{\frac{2}{5}x}$$

## 9
$$\ln(5+3x)$$

## 10
$$\mathrm{arctg}(9x)$$

## 11
$$\frac{1}{1+x^5}$$

## 12
$$\cos\left(-\frac{x}{2}\right)$$

## 13
$$e^{-\frac{3}{7}x}$$

## 14
$$\cos\left(\frac{17x}{20}\right)$$

## 15
$$\ln(1-8x)$$

## 16
$$\sin\frac{5x}{11}$$

## 17
$$\ln(4+5x)$$

## 18
$$\sin 15x$$

## 19
$$\frac{1}{1+x^{5}}$$

## 20
$$\mathrm{arctg}(-7x)$$

## 21
$$\sin(-5x)$$

## 22
$$e^{13x}$$

## 23
$$\frac{1}{1+x^{3}}$$

## 24
$$\mathrm{arctg}\left(\frac{3x}{2}\right)$$

## 25
$$\sqrt[5]{1+x}$$

## 26
$$\cos(-3x )$$
 
## 27
$$\frac{1}{1+{{x}^{3}}}$$

## 28
$$\cos(-\frac{x}{3} )$$

## 29
$$e^{-\frac{3}{5}x}$$

## 30
$$\cos\left(\frac{3x}{4}\right)$$

:::


## II. Сходимость функциональных рядов

### Задание 2. Найти радиус, интервал и область сходимости степенного ряда:

::: {.panel-tabset group='variant' .hide-tabs}

## &nbsp;

$$\text{Вариант не выбран}\phantom{\displaystyle\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{( 8n-1 )( 2n+3 )}{( 4n-6 )}}$$

$$\phantom{\displaystyle\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{\mathrm{arctg}~n}{1+{{n}^{2}}}}$$

$$\phantom{\displaystyle\underset{n=1}{\overset{\infty }{\mathop \sum }}{{( \frac{3{{n}^{2}}+1}{2{{n}^{2}}+1} )}^n}}$$

$$\phantom{\displaystyle\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{3n-2}{{{6}^n}}}$$


## 1
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{( n-2 )}^{3}}{{( x+3 )}^n}}{2n+3}$$

## 2
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{( x-5 )}^n}}{(3n-1)!\cdot{{2}^n}}$$

## 3
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{( x-5 )}^n}}{( 3n-1 )!\cdot{{2}^n}}$$

## 4
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{2n{{( x-1 )}^n}}{{{( 3n+1 )}^{2}}}$$

## 5
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{( x-6 )}^n}}{(n+2)\cdot{{3}^n}}$$

## 6
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{3n{{( x-2 )}^n}}{{{( 5n-8 )}^{3}}}$$

## 7
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{( x-2 )}^n}}{2n~{{3}^n}}$$

## 8
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{( x+2 )}^n}}{( 4n-1 )\cdot{{2}^n}}$$

## 9
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{\sqrt{n}{{( x-2 )}^n}}{{{n}^{2}}+1}$$

## 10
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{n}^{2}}{{( x+1 )}^n}}{( n+2 )!}$$

## 11
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{n{{( x-4 )}^n}}{( 2n+1 )!~}$$

## 12
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{( x+3 )}^n}}{( 3n-1 )\cdot{{2}^n}}$$

## 13
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{n}^{3}}{{( x+4 )}^n}}{( n+3 )!~}$$

## 14
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{n{{( x-4 )}^n}}{{{( 4n-1 )}^{3}}~}$$

## 15
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{( x+2 )}^n}}{( 2n+1 )\cdot{{3}^n}~}$$

## 16
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{( x+4 )}^n}}{( 4n+1 )\cdot{{3}^n}}$$

## 17
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{n}^{5}}{{( x+5 )}^n}}{( n+1 )~!}$$

## 18
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{( x-5 )}^n}}{( n+4 )~ln~( n+4 )}$$

## 19
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{( x-3 )}^n}}{( n+1 )\cdot{{5}^n}}$$

## 20
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{( n+1 )\cdot{{( x+7 )}^n}}{{{( n+3 )}^{2}}{{2}^{n-1}}}$$

## 21
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{( 3n-2 )\cdot{{( x-3 )}^n}}{{{( n+1 )}^{2}}\cdot{{2}^n}}$$

## 22
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{( x-2 )}^n}}{( 3n+1 )\cdot{{2}^n}}$$

## 23
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{( x-6 )}^n}}{( n+3 )\cdot{{2}^n}}$$

## 24
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{( x+6 )}^n}}{( 3n+1 )\cdot{{3}^n}}$$

## 25
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{n}^{2}}{{( x+5 )}^n}}{{{3}^n}}$$

## 26
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{n}^{2}}{{( x-3 )}^n}}{{{( {{n}^{4}}+1 )}^{2}}}$$

## 27
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{2n(x+6)}^n}}{(2n+4)^3}$$

## 28
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{(x-2)}^n}}{(2n-1)\cdot{{5}^n}}$$

## 29
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{n}^{3}}{{(x-3)}^n}}{{{4}^n}}$$

## 30
$$\underset{n=1}{\overset{\infty }{\mathop \sum }}\frac{{{n}^{2}}{{(x-2)}^n}}{{{( {{n}^{2}}-1 )}^{2}}}$$

:::

